services:
  backend:
    build:
      context: ./todo-app-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./todo-app-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5174:80"   
    depends_on:
      - backend
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: tododb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - appnet

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge